// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AppEventLog.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class BaseInfo;
@class BusinessInfo;
@class Params;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum Platform

/** 设备平台 */
typedef GPB_ENUM(Platform) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  Platform_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  Platform_PNone = 0,
  Platform_Ios = 1,
  Platform_Android = 2,
  Platform_Web = 3,
  Platform_H5 = 4,
};

GPBEnumDescriptor *Platform_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL Platform_IsValidValue(int32_t value);

#pragma mark - AppEventLogRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface AppEventLogRoot : GPBRootObject
@end

#pragma mark - Params

typedef GPB_ENUM(Params_FieldNumber) {
  Params_FieldNumber_Key = 1,
  Params_FieldNumber_Value = 2,
};

@interface Params : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *key;

@property(nonatomic, readwrite, copy, null_resettable) NSString *value;

@end

#pragma mark - BaseInfo

typedef GPB_ENUM(BaseInfo_FieldNumber) {
  BaseInfo_FieldNumber_AppName = 1,
  BaseInfo_FieldNumber_Timestamp = 2,
  BaseInfo_FieldNumber_Platform = 3,
  BaseInfo_FieldNumber_Uuid = 4,
  BaseInfo_FieldNumber_Fc = 5,
};

/**
 * 基础信息
 **/
@interface BaseInfo : GPBMessage

/** 应用名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *appName;

/** 时间戳 */
@property(nonatomic, readwrite) int32_t timestamp;

/** 平台 */
@property(nonatomic, readwrite) Platform platform;

/** uuid */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uuid;

/** 推广渠道名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *fc;

@end

/**
 * Fetches the raw value of a @c BaseInfo's @c platform property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t BaseInfo_Platform_RawValue(BaseInfo *message);
/**
 * Sets the raw value of an @c BaseInfo's @c platform property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetBaseInfo_Platform_RawValue(BaseInfo *message, int32_t value);

#pragma mark - BusinessInfo

typedef GPB_ENUM(BusinessInfo_FieldNumber) {
  BusinessInfo_FieldNumber_UserId = 1,
  BusinessInfo_FieldNumber_Timestamp = 2,
  BusinessInfo_FieldNumber_Event = 3,
  BusinessInfo_FieldNumber_ParamsArray = 4,
};

/**
 * 业务信息
 **/
@interface BusinessInfo : GPBMessage

/** 用户uid */
@property(nonatomic, readwrite) int32_t userId;

/** 时间戳 */
@property(nonatomic, readwrite) int32_t timestamp;

@property(nonatomic, readwrite, copy, null_resettable) NSString *event;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Params*> *paramsArray;
/** The number of items in @c paramsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger paramsArray_Count;

@end

#pragma mark - LogInfo

typedef GPB_ENUM(LogInfo_FieldNumber) {
  LogInfo_FieldNumber_BaseInfo = 1,
  LogInfo_FieldNumber_BusinessInfoArray = 2,
};

/**
 * 日志信息
 **/
@interface LogInfo : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) BaseInfo *baseInfo;
/** Test to see if @c baseInfo has been set. */
@property(nonatomic, readwrite) BOOL hasBaseInfo;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<BusinessInfo*> *businessInfoArray;
/** The number of items in @c businessInfoArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger businessInfoArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
